# Generated by Django 4.0.8 on 2023-01-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
